name: Build Binaries

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v4
        with:
          name: sci-shot-${{ matrix.os }}
          path: target/release/sci-shot*
          if-no-files-found: error

